version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_HOST: ${DB_HOST}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - /var/lib/postgresql/data
